---
title: "Electricpower consumption"
author: "Sooraj Bhagya"
date: "June 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sqldf)
library(plyr)
library(dplyr)
library(lubridate)
```

## 


```{r Unzip data,cache=T,include=T,echo=TRUE}
Req.data<-read.csv.sql('household_power_consumption.txt',"select * from file where Date ='1/2/2007' or Date ='2/2/2007'",  sep=';')
datetime<-as.POSIXlt(as.character(paste(dmy(as.character(Req.data$Date)),(Req.data$Time))))
req.data.date<-(as.data.frame(cbind(Req.data,datetime)))
```

## Plot1


```{r plot1, echo=FALSE}
hist(Req.data$Global_active_power,col='Red',xlab = "Global Active Power (kilowatts)")
 dev.copy(png, file="plot1.png", width=480, height=480)
        dev.off()
```

## Plot2
```{r plot2, echo=FALSE}
 plot(req.data.date$datetime,req.data.date$Global_active_power,type = 'l',ylab="Global Active Power (kilowatts)",xlab ="")
 dev.copy(png, file="plot2.png", width=480, height=480)
        dev.off()
```


## Plot3
```{r plot3, echo=FALSE}
plot(req.data.date$datetime,req.data.date$Sub_metering_1,ylab="Energy submetering",xlab ="",type = 'l')
lines(req.data.date$datetime,req.data.date$Sub_metering_2,col='red')
lines(req.data.date$datetime,req.data.date$Sub_metering_3,col='blue')
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
 dev.copy(png, file="plot3.png", width=480, height=480)
        dev.off()
```

## Plot4
```{r plot4, echo=FALSE}
par(mfrow=c(2,2))
par(mar=c(5,5,2,1))
plot(req.data.date$datetime,req.data.date$Global_active_power,type = 'l',ylab="Global Active Power (kilowatts)",xlab ="")
plot(req.data.date$datetime,req.data.date$Voltage,type = 'l',ylab="Voltage",xlab ="datetime")
plot(req.data.date$datetime,req.data.date$Sub_metering_1,ylab="Energy submetering",xlab ="",type = 'l')
lines(req.data.date$datetime,req.data.date$Sub_metering_2,col='red')
lines(req.data.date$datetime,req.data.date$Sub_metering_3,col='blue')
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
plot(req.data.date$datetime,req.data.date$Global_reactive_power,type = 'l',ylab="Voltage",xlab ="datetime")
 dev.copy(png, file="plot4.png", width=480, height=480)
        dev.off()
```


