library(sqldf)
library(plyr)
library(dplyr)
library(lubridate)
Req.data<-read.csv.sql('household_power_consumption.txt',"select * from file where Date ='1/2/2007' or Date ='2/2/2007'",  sep=';')
datetime<-as.POSIXlt(as.character(paste(dmy(as.character(Req.data$Date)),(Req.data$Time))))
req.data.date<-(as.data.frame(cbind(Req.data,datetime)))
plot(req.data.date$datetime,req.data.date$Sub_metering_1,ylab="Energy submetering",xlab ="",type = 'l')
lines(req.data.date$datetime,req.data.date$Sub_metering_2,col='red')
lines(req.data.date$datetime,req.data.date$Sub_metering_3,col='blue')
legend("topright", col=c("black","red","blue"), c("Sub_metering_1  ","Sub_metering_2  ", "Sub_metering_3  "),lty=c(1,1), lwd=c(1,1))
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()