library(sqldf)
library(plyr)
library(dplyr)
library(lubridate)
Req.data<-read.csv.sql('household_power_consumption.txt',"select * from file where Date ='1/2/2007' or Date ='2/2/2007'",  sep=';')
datetime<-as.POSIXlt(as.character(paste(dmy(as.character(Req.data$Date)),(Req.data$Time))))
req.data.date<-(as.data.frame(cbind(Req.data,datetime)))
plot(req.data.date$datetime,req.data.date$Global_active_power,type = 'l',ylab="Global Active Power (kilowatts)",xlab ="")
dev.copy(png, file="plot2.png", width=480, height=480)
dev.off()